# Ansible Azure Pipeline
trigger:
  - master

pool:
  name: 'default'

steps:

- script: |
    echo "First pipeline Script"
    echo "Another line of code"

- script: |
    sudo apt update -y
    sudo apt install -y ansible
    ansible --version
  displayName: "Installing Ansible"

- script: |
    sudo apt install -y ansible-lint
    ansible-lint --version
  displayName: "Installing Ansible-lint"

- script: |
    ansible-lint
  displayName: "Run ansible-lint"

- script: |
    ANSIBLE_HOST_KEY_CHECKING=False
    ansible-playbook \
      -u ubuntu \
      -i ./host_inventory \
      --private-key '/home/ubuntu/.ssh/gp-13-july-22.pem' \
      ./playbooks/apache-install.yml 
  displayName: "Installing Apache"


