# Ansible Azure Pipeline
trigger:
  - master

pool:
  name: 'ip-10-0-0-19'

steps:

- script: |
    echo "First pipeline Script"
    echo "Another line of code"

- script: |
    sudo apt update -y
    sudo apt install -y ansible
    ansible --version
  displayName: "Installing Ansible"
