name: Ansible-Github Actions
on: push

jobs:

  repo_updated:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master

  install_ansible:
    runs-on: self-hosted
    steps:
      - name: 'Installing Ansible'
        run: |
          sudo apt-get update -y
          sudo apt install -y ansible ansible-lint
          echo '*******Install Test*******'
          which ansible ansible-lint

  run_ansible_lint:
    needs: [install_ansible]
    runs-on: self-hosted
    steps:
      - name: 'Linting Ansible Playbooks'
        run: ansible-lint

  install_apache:
    needs: [run_ansible_lint]
    runs-on: self-hosted
    steps:
      - name: 'Installing Apache'
        run: |
          workdir="${GITHUB_WORKSPACE}"
          echo '*******Note Work Directory******* '
          echo $workdir
          ANSIBLE_HOST_KEY_CHECKING=False \
          ansible-playbook -u ubuntu \
          -i $workdir/host_inventory \
          $workdir/playbooks/apache-install.yml \
          --private-key '/home/ubuntu/.ssh/gp-13-july-22.pem'

  website-update:
    needs: [install_apache]
    runs-on: self-hosted
    steps:
      - name: 'Website Updating'
        run: |
          workdir="${GITHUB_WORKSPACE}"
          echo '*******Note Work Directory******* '
          echo $workdir
          ANSIBLE_HOST_KEY_CHECKING=False \
          export ANSIBLE_ROLES_PATH=$workdir/roles && \
          ansible-playbook -u ubuntu \
          -i $workdir/host_inventory \
          $workdir/playbooks/website-update.yml \
          --private-key '/home/ubuntu/.ssh/gp-13-july-22.pem'

  website-test:
    needs: [website_update]
    runs-on: self-hosted
    steps:
      - name: 'Website Testing'
        run: |
          workdir="${GITHUB_WORKSPACE}"
          echo '*******Note Work Directory******* '
          echo $workdir
          ANSIBLE_HOST_KEY_CHECKING=False \
          export ANSIBLE_ROLES_PATH=$workdir/roles && \
          ansible-playbook -u ubuntu \
          -i $workdir/host_inventory \
          $workdir/playbooks/website-test.yml \
          --private-key '/home/ubuntu/.ssh/gp-13-july-22.pem'
