name: Ansible-Github Actions
on: push

jobs:

  repo_updated:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master

  install_ansible:
    runs-on: self-hosted
    steps:
      - name: 'Installing Ansible'
        run: |
          sudo apt-get update -y
          sudo apt install -y ansible ansible-lint
          echo '*******Install Test*******'
          which ansible ansible-lint

  run_ansible_lint:
    needs: [install_ansible]
    runs-on: self-hosted
    steps:
      - name: 'Linting Ansible Playbooks'
        run: ansible-lint

  install_apache:
    needs: [run_ansible_lint]
    runs-on: self-hosted
    steps:
      - name: 'Installing Apache'
        run: |
          workdir="${GITHUB_WORKSPACE}"
          ANSIBLE_HOST_KEY_CHECKING=False \
          ansible-playbook -u ubuntu \
          -i $workdir/host_inventory \
          $workdir/playbooks/apache-install.yml \
          --private-key 'home/ubuntu/.ssh/gp-13-july-22.pem'
